amap:
  key: "key=35092c64281631ea94f4f220ce6a1289" #注意：我这个key每天只有2k调用量，需要申请自己的可以到https://lbs.amap.com/dev/key/app申请
  url_prefix: "https://restapi.amap.com/v3/config/district?"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 你数据库的密码
    url: jdbc:mysql://localhost:3306/amap_district?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
    database: mysql
